if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT OR NOT DEFINED SYMBOL)
    message(FATAL_ERROR "INPUT, OUTPUT and SYMBOL are required")
endif()
file(READ "${INPUT}" shader_hex HEX)
string(LENGTH "${shader_hex}" hex_length)
math(EXPR remainder "${hex_length} % 8")
if(hex_length LESS 40 OR NOT remainder EQUAL 0)
    message(FATAL_ERROR "Invalid SPIR-V size: ${INPUT}")
endif()
string(SUBSTRING "${shader_hex}" 0 8 magic)
if(NOT magic STREQUAL "03022307")
    message(FATAL_ERROR "Invalid SPIR-V byte order or magic: ${INPUT}")
endif()
string(REGEX REPLACE "([0-9a-f][0-9a-f])([0-9a-f][0-9a-f])([0-9a-f][0-9a-f])([0-9a-f][0-9a-f])" "0x\\4\\3\\2\\1u,\n" shader_words "${shader_hex}")
file(WRITE "${OUTPUT}.tmp" "inline constexpr uint32_t ${SYMBOL}[] = {\n${shader_words}};\n")
file(RENAME "${OUTPUT}.tmp" "${OUTPUT}")
