file(REMOVE_RECURSE "${DESTINATION}")
file(COPY "${SOURCE}/vanilla/font" DESTINATION "${DESTINATION}/vanilla" PATTERN ".DS_Store" EXCLUDE)
file(COPY "${SOURCE}/vanilla/__brarchive/font.brarchive" DESTINATION "${DESTINATION}/vanilla/__brarchive")
get_filename_component(data "${SOURCE}" DIRECTORY)
if(IS_DIRECTORY "${data}/gui/dist/hbui")
    file(COPY "${data}/gui/dist/hbui" DESTINATION "${BUNDLE}/gui/dist" PATTERN ".DS_Store" EXCLUDE)
endif()
file(COPY_FILE "${CA_BUNDLE}" "${BUNDLE}/cert.pem" ONLY_IF_DIFFERENT)
file(COPY_FILE "${ICON}" "${BUNDLE}/icon.png" ONLY_IF_DIFFERENT)
file(MAKE_DIRECTORY "${DESTINATION}/vanilla/ui")
file(COPY_FILE "${TOUCH_UI}" "${DESTINATION}/vanilla/ui/kestrel_touch_controls.json" ONLY_IF_DIFFERENT)
