file(REMOVE_RECURSE "${DESTINATION}")
file(COPY "${SOURCE}/vanilla/font" DESTINATION "${DESTINATION}/vanilla" PATTERN ".DS_Store" EXCLUDE)
file(COPY "${SOURCE}/vanilla/__brarchive/font.brarchive" DESTINATION "${DESTINATION}/vanilla/__brarchive")
get_filename_component(data "${SOURCE}" DIRECTORY)
if(IS_DIRECTORY "${data}/gui/dist/hbui")
    file(COPY "${data}/gui/dist/hbui" DESTINATION "${BUNDLE}/gui/dist" PATTERN ".DS_Store" EXCLUDE)
endif()
file(COPY_FILE "${CA_BUNDLE}" "${BUNDLE}/cert.pem" ONLY_IF_DIFFERENT)
file(COPY_FILE "${ICON}" "${BUNDLE}/icon.png" ONLY_IF_DIFFERENT)
file(MAKE_DIRECTORY "${DESTINATION}/vanilla/ui")
file(COPY_FILE "${TOUCH_UI}" "${DESTINATION}/vanilla/ui/kestrel_touch_controls.json" ONLY_IF_DIFFERENT)

# The free fonts the app falls back to, cached between builds and checked against their pinned SHA-256.
file(MAKE_DIRECTORY "${FONT_CACHE}" "${BUNDLE}/fonts")
file(STRINGS "${FONTS}" fontLines REGEX "^[^#]")
foreach(line IN LISTS fontLines)
    string(REPLACE " " ";" fields "${line}")
    list(GET fields 0 name)
    list(GET fields 1 hash)
    list(GET fields 2 url)
    set(cached "${FONT_CACHE}/${name}")
    set(current "")
    if(EXISTS "${cached}")
        file(SHA256 "${cached}" current)
    endif()
    if(NOT current STREQUAL hash)
        file(DOWNLOAD "${url}" "${cached}" EXPECTED_HASH SHA256=${hash} STATUS status)
        list(GET status 0 code)
        if(NOT code EQUAL 0)
            message(FATAL_ERROR "Could not download ${name}: ${status}")
        endif()
    endif()
    file(COPY_FILE "${cached}" "${BUNDLE}/fonts/${name}" ONLY_IF_DIFFERENT)
endforeach()
